package UIPackage;

import ClassPackage.UserClass;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class AdminPage extends javax.swing.JFrame {

    UserClass userClass = new UserClass(); //creating an instance of userClass

    public AdminPage() {
        initComponents();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adminTabs = new javax.swing.JTabbedPane();
        createUserAccountsTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        btnCreateAccount = new javax.swing.JButton();
        allUserAccountsTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUserAccounts = new javax.swing.JTable();
        btnDeleteUser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Details Management System");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Welcome Administrator");

        adminTabs.setBackground(new java.awt.Color(204, 204, 255));
        adminTabs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adminTabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                adminTabsStateChanged(evt);
            }
        });

        createUserAccountsTab.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Enter a User Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Fill the Form to create a user account");

        txtUserName.setBackground(new java.awt.Color(204, 204, 255));
        txtUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Enter a Password");

        txtPassword.setBackground(new java.awt.Color(204, 204, 255));
        txtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Confirm Password");

        txtConfirmPassword.setBackground(new java.awt.Color(204, 204, 255));
        txtConfirmPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Select User Type");

        cmbUserType.setBackground(new java.awt.Color(204, 204, 255));
        cmbUserType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cmbUserType.setForeground(new java.awt.Color(51, 51, 51));
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Assistant" }));
        cmbUserType.setBorder(null);

        btnCreateAccount.setBackground(new java.awt.Color(49, 39, 38));
        btnCreateAccount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createUserAccountsTabLayout = new javax.swing.GroupLayout(createUserAccountsTab);
        createUserAccountsTab.setLayout(createUserAccountsTabLayout);
        createUserAccountsTabLayout.setHorizontalGroup(
            createUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserAccountsTabLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(createUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createUserAccountsTabLayout.createSequentialGroup()
                        .addGroup(createUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createUserAccountsTabLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6))
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        createUserAccountsTabLayout.setVerticalGroup(
            createUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserAccountsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        adminTabs.addTab("Create user Accounts", createUserAccountsTab);

        allUserAccountsTab.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        tableUserAccounts.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        tableUserAccounts.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUserAccounts);

        btnDeleteUser.setBackground(new java.awt.Color(216, 34, 15));
        btnDeleteUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allUserAccountsTabLayout = new javax.swing.GroupLayout(allUserAccountsTab);
        allUserAccountsTab.setLayout(allUserAccountsTabLayout);
        allUserAccountsTabLayout.setHorizontalGroup(
            allUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allUserAccountsTabLayout.createSequentialGroup()
                .addGroup(allUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(allUserAccountsTabLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
        allUserAccountsTabLayout.setVerticalGroup(
            allUserAccountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allUserAccountsTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteUser)
                .addContainerGap())
        );

        adminTabs.addTab("All User Accounts", allUserAccountsTab);

        btnLogout.setBackground(new java.awt.Color(49, 39, 38));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LogOut");
        btnLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(adminTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel5)))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed

        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        String userType = cmbUserType.getSelectedItem().toString();
        boolean valid = true;

        boolean userNamefound = userClass.userNameFound(userName);

        if (txtUserName.getText().isEmpty() || txtPassword.getText().isEmpty() || txtConfirmPassword.getText().isEmpty() || cmbUserType.getSelectedItem().toString().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Fields can't be empty ", "Create User Accounts", JOptionPane.WARNING_MESSAGE);
           
            valid = false;

        } else {
            if (userNamefound) {

                JOptionPane.showMessageDialog(null, "User Name Already Registered , Try with a different User Name ", "Create User Accounts", JOptionPane.WARNING_MESSAGE);
                
                valid = false;
                
                txtUserName.setText("");

            } else if (txtPassword.getText().length() < 5) {

                JOptionPane.showMessageDialog(null, "Password must have 5 characters ", "Create User Accounts", JOptionPane.WARNING_MESSAGE);
                
                txtPassword.setText("");
                txtConfirmPassword.setText("");
                
                valid = false;

            } else if (!txtPassword.getText().equals(txtConfirmPassword.getText())) {

                JOptionPane.showMessageDialog(null, "Password and confirm password should match ", "Create User Accounts", JOptionPane.WARNING_MESSAGE);
                txtPassword.setText("");
                txtConfirmPassword.setText("");
                valid = false;

            } else if (userType.equals("Manager") && userClass.ManagerFound(userType)) {

                JOptionPane.showMessageDialog(null, "User account for the HR manager is already created", "Create User Accounts", JOptionPane.ERROR_MESSAGE);
                valid = false;

            }

        }
        if (valid) {

            //initializing another object to use the constructor in user class
            UserClass newUser = new UserClass(userName, password, userType);

            if (newUser.addNewUser()) {

                JOptionPane.showMessageDialog(null, "User added successfully", "Create User Accounts", JOptionPane.INFORMATION_MESSAGE);

                txtUserName.setText("");
                txtPassword.setText("");
                txtConfirmPassword.setText("");

            } else {

                JOptionPane.showMessageDialog(null, "Sorry! Something went wrong with the application, Will be fixing it soon.", "Create User Accounts", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnCreateAccountActionPerformed


    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed

        JTable userTable = tableUserAccounts;
        int selectedRow = userTable.getSelectedRow();

        if (selectedRow < 0) {

            JOptionPane.showMessageDialog(null, "Please select the User to delete ", "Delete User Accounts", JOptionPane.WARNING_MESSAGE);
        }

        if (selectedRow >= 0) {

            String userName = (String) userTable.getValueAt(selectedRow, 0);  // table model value casting into String  
            boolean result = userClass.deleteAUser(userName);

            if (result) {

                JOptionPane.showMessageDialog(null, "User account deleted from the system", "Delete User Accounts", JOptionPane.INFORMATION_MESSAGE);
                
                DefaultTableModel defaultTableModel = userClass.viewAllUsers();
                tableUserAccounts.setModel(defaultTableModel);

            } else {

                JOptionPane.showMessageDialog(null, "Sorry! Something went wrong with the application, Will be fixing it soon.", "Delete User Accounts", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void adminTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_adminTabsStateChanged

        int selectedTab = adminTabs.getSelectedIndex();
        
        if (selectedTab == 0) {
            
            txtUserName.setText("");
            txtPassword.setText("");
            txtConfirmPassword.setText("");

        } else if (selectedTab == 1) {
            
            DefaultTableModel defaultTableModel = userClass.viewAllUsers();
            tableUserAccounts.setModel(defaultTableModel);

        }
    }//GEN-LAST:event_adminTabsStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane adminTabs;
    private javax.swing.JPanel allUserAccountsTab;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JPanel createUserAccountsTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUserAccounts;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
